Repository SciTools/cf-units, pull requests merged in 2021-06, with the labels that each got.

#168 Updates for cftime 1.5.0
  cf_units/__init__.py
  cf_units/tests/integration/test__num2date_to_nearest_second.py
  cf_units/tests/test_unit.py
  doc/source/utilities.rst
Labels: SemVer: Major

#175 Switched from Travis to Cirrus. Updated requirements architecture.
  .cirrus.yml
  .travis.yml
  INSTALL
  README.md
  requirements-dev.txt
  requirements.txt
  requirements/cf-units.yml
  requirements/py37.yml
  requirements/py38.yml
  requirements/py39.yml
  setup.py
Labels: Experience: Medium, Type: Infrastructure, Type: Testing

#176 Setup architecture overhaul
  .coveragerc
  .gitignore
  .stickler.yml
  MANIFEST.in
  cf_units/__init__.py
  cf_units/_version.py
  cf_units/tests/test_coding_standards.py
  codecov.yml
  pyproject.toml
  setup.cfg
  setup.py
  versioneer.py
Labels: Experience: High, Type: Infrastructure

#172 num2pydate
  cf_units/__init__.py
  cf_units/tests/integration/test__num2date_to_nearest_second.py
  cf_units/tests/integration/test_num2date.py
  cf_units/tests/integration/test_num2pydate.py
  cf_units/tests/test_unit.py
  doc/source/utilities.rst
Labels: Type: Enhancement

#181 Implement Read the docs.
  .readthedocs.yml
  README.md
  doc/source/conf.py
  doc/source/index.rst
  requirements/py37.yml
  requirements/py38.yml
  requirements/py39.yml
  setup.cfg
Labels: Type: Documentation

#183 Persist calendar when discarding cftime microsecond
  cf_units/__init__.py
  cf_units/tests/unit/test__discard_microsecond.py
  cf_units/tests/unit/unit/test_Unit.py
  pyproject.toml
Labels: New: Pull Request, Release: Patch, Type: Bug
