Repository SciTools/cf-units, pull requests merged in 2024-09, with the labels that each got.

#461 Fully support Python 3.12
  .github/workflows/ci-locks.yml
  .github/workflows/ci-tests.yml
  cf_units/tests/test_coding_standards.py
  pyproject.toml
  setup.cfg
  tox.ini
Labels: Type: Infrastructure, Type: Testing

#456 Add repo-review
  .pre-commit-config.yaml
  pyproject.toml
Labels: Type: Infrastructure, repo-checking

#467 [DOCS] Updated docstring for num2date
  cf_units/__init__.py
Labels: Type: Documentation

#423 Make antlr optional
  cf_units/tests/integration/parse/test_graph.py
  cf_units/tests/integration/parse/test_parse.py
  cf_units/tests/test_tex.py
  requirements/cf-units.yml
  setup.cfg
Labels: Type: Infrastructure, community

#483 [DOCS] Update docstring for date2num (module function)
  cf_units/__init__.py
Labels: Type: Documentation

#489 Read the Docs fixes and modernisation
  .readthedocs.yml
  docs/source/conf.py
Labels: Type: Documentation

#493 Artifact Actions v4
  .github/workflows/ci-locks.yml
  .github/workflows/ci-wheels.yml
Labels: Type: Infrastructure
